# Generated by Django 4.2.7 on 2024-02-24 11:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ums", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="user_type",
            field=models.TextField(
                choices=[("Client", "Client"), ("Admin ", "Admin")],
                default="Client",
                verbose_name="user_type",
            ),
        ),
    ]
