# Generated by Django 4.2.7 on 2024-02-19 19:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="package_price_option",
            field=models.TextField(
                blank=True,
                choices=[
                    ("day_weekday", "day_weekday"),
                    ("overnight_weekday", "overnight_weekday"),
                    ("day_weekend", "day_weekend"),
                    ("overnight_weekend", "overnight_weekend"),
                ],
                null=True,
                verbose_name="package_option",
            ),
        ),
    ]
