# Generated by Django 4.2.7 on 2024-02-21 19:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0003_webhookbackup_applogs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="package",
            name="caution_fee",
            field=models.DecimalField(
                decimal_places=2, help_text="the caution fee", max_digits=19
            ),
        ),
        migrations.AlterField(
            model_name="package",
            name="day_weekday_price",
            field=models.DecimalField(
                decimal_places=2, help_text="weekday day booking price", max_digits=19
            ),
        ),
        migrations.AlterField(
            model_name="package",
            name="day_weekend_price",
            field=models.DecimalField(
                decimal_places=2, help_text="weekend day booking price", max_digits=19
            ),
        ),
        migrations.AlterField(
            model_name="package",
            name="extra_guest_fee",
            field=models.DecimalField(
                decimal_places=2, help_text="the cost of extra guest", max_digits=19
            ),
        ),
        migrations.AlterField(
            model_name="package",
            name="overnight_weekday_price",
            field=models.DecimalField(
                decimal_places=2,
                help_text="weekday overnight booking price",
                max_digits=19,
            ),
        ),
        migrations.AlterField(
            model_name="package",
            name="overnight_weekend_price",
            field=models.DecimalField(
                decimal_places=2,
                help_text="weekend overnight booking price",
                max_digits=19,
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="caution_fee",
            field=models.DecimalField(
                decimal_places=2, help_text="the caution fee", max_digits=19
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="discount_price",
            field=models.DecimalField(
                decimal_places=2, help_text="the cost of the room", max_digits=19
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="price",
            field=models.DecimalField(
                decimal_places=2, help_text="the cost of the room", max_digits=19
            ),
        ),
    ]
