# Generated by Django 4.2.7 on 2024-02-24 11:06

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("ums", "0002_profile_user_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("booking", "0004_alter_package_caution_fee_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookingInfo",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Created at",
                    ),
                ),
                (
                    "lastmodified_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Last modified at",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="active?"),
                ),
                ("phone", models.CharField(blank=True, max_length=40, null=True)),
                ("phone_verified", models.BooleanField(default=False)),
                ("full_name", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "company_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("address", models.TextField(blank=True, null=True)),
                (
                    "corporate_rep",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("number_of_guests", models.IntegerField(default=1)),
                (
                    "nature_of_business",
                    models.CharField(blank=True, max_length=400, null=True),
                ),
                (
                    "client_type",
                    models.TextField(
                        choices=[("Personal", "Personal"), ("Corporate ", "Corporate")],
                        default="Personal",
                        verbose_name="template_view",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "lastmodified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_lastmodified",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last modified by",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ums.profile",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
                "abstract": False,
            },
            bases=(core.models.CloneableMixin, models.Model),
        ),
        migrations.AddField(
            model_name="order",
            name="booking_info",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="booking.bookinginfo",
            ),
        ),
    ]
