# Generated by Django 4.2.7 on 2024-02-24 23:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0005_bookinginfo_order_booking_info"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookinginfo",
            name="other_phone",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
