# Generated by Django 4.2.7 on 2024-02-24 23:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0006_bookinginfo_other_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookinginfo",
            name="client_type",
            field=models.TextField(
                choices=[("Personal", "Personal"), ("Corporate ", "Corporate")],
                default="Personal",
                verbose_name="client_type",
            ),
        ),
    ]
