# Generated by Django 4.2.7 on 2024-02-25 19:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0007_alter_bookinginfo_client_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="stock_availability",
            field=models.IntegerField(default=1),
        ),
    ]
