# Generated by Django 4.2.7 on 2024-02-25 20:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0009_orderitem_rate"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="extra_guest",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="package",
            name="day_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="day booking price",
                max_digits=19,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="package",
            name="overnight_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="overnight booking price",
                max_digits=19,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="package_price_option",
            field=models.TextField(
                blank=True,
                choices=[("day", "day"), ("overnight", "overnight")],
                null=True,
                verbose_name="package_option",
            ),
        ),
        migrations.AlterField(
            model_name="package",
            name="day_weekday_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="weekday day booking price",
                max_digits=19,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="package",
            name="day_weekend_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="weekend day booking price",
                max_digits=19,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="package",
            name="overnight_weekday_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="weekday overnight booking price",
                max_digits=19,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="package",
            name="overnight_weekend_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="weekend overnight booking price",
                max_digits=19,
                null=True,
            ),
        ),
    ]
