# Generated by Django 4.2.7 on 2024-02-26 23:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0010_orderitem_extra_guest_package_day_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="package",
            name="position",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="room",
            name="position",
            field=models.IntegerField(default=1),
        ),
    ]
