# Generated by Django 4.2.7 on 2024-02-27 07:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0011_package_position_room_position"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="is_complimentary",
            field=models.BooleanField(default=False),
        ),
    ]
