# Generated by Django 4.2.7 on 2024-02-27 07:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0012_orderitem_is_complimentary"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="room",
            name="stock_availability",
        ),
    ]
